# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jbDVbsZMYLIwZA17oq1Lyz_zWiy9MOm4
"""

# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st
import altair as alt
import os
import warnings
warnings.filterwarnings('ignore')

# import dataset
@st.cache
def load_data():
    df = pd.read_csv('final_merged.csv')
    return df

df = load_data()

# import side bar
st.sidebar.header('Please Filter Here')
Area_Name = st.sidebar.multiselect(
    'Select Area of Interest',
    options = df['Area_Name'].unique(),
    default = df['Area_Name'].unique()
)

st.dataframe(df)

# year side bar
Year = st.sidebar.multiselect(
    'Select Year',
    options = df['Year'].unique(),
    default = df['Year'].unique()
)

###main_page
df_select = df.query('Area_Name== @Area_Name & Year == @Year')

# if selection is not available then stop
if df_select.empty:
  st.warning('No data available based on the current filter settings')
  st.stop()

st.title('Terrestrial Ecosystems Biodiversity Trends in Kenyan Protected Areas')
st.markdown('##')

#calculate
average_ndvi = df_select['mean_ndvi'].mean()
average_ndwi = df_select['mean_ndwi'].mean()
average_bsi = df_select['mean_bsi'].mean()
average_rainfall = df_select['Mean_Rainfall_mm'].mean()
risk_factor = df_select['Risk_Factor'].mean()
area_trend = df_select['Area_Trend']
area_risk_trend = df_select['Area_Risk_Trend']

# columns
first_column, second_column, third_column, fourth_column = st.columns(4)

with first_column:
  st.subheader('Average NDVI')
  st.subheader(f'{average_ndvi:.2f}')

with second_column:
  st.subheader('Average NDWI')
  st.subheader(f'{average_ndwi:.2f}')

with third_column:
  st.subheader('Average BSI')
  st.subheader(f'{average_bsi:.2f}')

with fourth_column:
  st.subheader('Average Rainfall')
  st.subheader(f'{average_rainfall:.2f}')

st.divider()

# line graph to show index
df = df.select(['Year', 'mean_ndvi', 'mean_ndwi', 'mean_bsi', 'Mean_Rainfall_mm'])
    # Melt the DataFrame for Altair
df_melted = df.melt(id_vars=['Year'],
                    value_vars=['NDVI', 'NDWI', 'BSI', 'Rainfall'],
                    var_name='Index Name',
                    value_name='Index Value')

    # Create the Altair plot
chart = alt.Chart(df_melted).mark_line().encode(
    x=alt.X('Year', axis=alt.Axis(format="%Y-%m-%d")),
    y=alt.Y('Index Value'),
    color='Index Name',
    tooltip=['Year', 'Index Name', 'Index Value']
).properties(
    title=f'Environmental Indices for {Area_Name}'
).interactive()
